version: '3'
services:
  judge-host:
    image: yuzhanglong/online-judge-host:20d59a7323d9a264db3d2426fc18d117ce5195f9
    ports:
      - "8080:8080"
    volumes:
      - /home/YuJudge/judgeEnvironment/resolutions:/home/judgeEnvironment/resolutions
      - /home/YuJudge/judgeEnvironment/submissions:/home/judgeEnvironment/submissions
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JUDGE_HOST_USER_ID: yzl
      JUDGE_HOST_USER_SECRET: yzl
      JUDGE_HOST_SECRET_KEY: secret
  redis:
    image: redis
    command:
      redis-server --port 6379 --appendonly yes
    volumes:
      - /home/YuJudge/redis:/data
